### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by bebo-dot-dev** [sipgate-io/sipgateio-sendsms-python#1]
I created a new personal access token in my sipgate basic account and ensured that this token had `sessions:sms:write` scope, only `sessions:sms:write` scope and no other access scope(s) whatsoever. 

This personal access token doesn't work, request attempts to https://api.sipgate.com/v2/sessions/sms fail with a 403 response.

Requests to https://api.sipgate.com/v2/sessions/sms using my regular sipgate basic account username and password work as expected, an sms was sent/received so it would appear that personal access token creation is currently somehow broken or access tokens require more than solely `sessions:sms:write` scope to work correctly.

**Comment by chboland** [comment]
I can confirm that `sessions:sms:write` scope is not enough. If I select 'all scopes' when creating a token, sending sms works as expected. I suggest the example is updated with the additional scopes needed.

**Comment by nilsreck** [comment]
Hello,

we were not able to reproduce the error by following the procedure described in the Readme. 
You can find an overview of common HTTP errors and how to fix those [here](https://github.com/sipgate-io/sipgateio-sendsms-python#http-errors). 
Regarding 403, please make sure that you have selected a valid SMS extension (for example `s0`) by following the explanations given in the [.env.example](https://github.com/sipgate-io/sipgateio-sendsms-python/blob/master/.env.example) or the Readme. Another reason that the 403 error occurs may be that you do not have permissions to make the necessary API requests, for example by not having booked the SMS feature.

Best regards,
Nils from sipgate.io

**Comment by bebo-dot-dev** [comment]
hey Nils, thanks for your reply.

I'm not positioned to test this any more but if it works as expected with a PAT that only has the sessions:sms:write scope and no other scopes then great, fixed! If that's the case maybe you guys have fixed something between when I opened this and today.

Either way your call if you want to close this down. 

Thank you, Joe

**Comment by adam-jones-net** [comment]
> I can confirm that `sessions:sms:write` scope is not enough. If I select 'all scopes' when creating a token, sending sms works as expected. I suggest the example is updated with the additional scopes needed.

I added 2 groups of privileges, both sessions and sms groups and it worked with this
